### ISSUE TITLE
Framework bypass trap: safe wrappers lack recovery paths; stage-hash broken on first invocation

### ISSUE THREAD

**Issue by jordandm** [the-agency-ai/the-agency#128]
**Type:** bug

# BUG-0001: Framework bypass trap — safe wrappers lack recovery paths; stage-hash broken

**Status:** Open
**Reported:** 2026-04-15
**Assigned To:** captain
**Workstream:** housekeeping

## Description

Two related issues in the Agency 2.0 framework push agents toward raw-git bypasses of the safe-tools discipline:

1. **Missing recovery paths in safe wrappers.** Neither `git-safe` nor `git-captain` exposes `reset` (soft, mixed, or hard). When an agent needs to undo a local commit — e.g. to redo it properly through `/git-safe-commit` after a process violation — there is no sanctioned path. The only options are (a) raw `git reset` (another bypass), (b) leave the bad commit and flag it, or (c) stop and extend tooling. This creates a trap where recovering from a bypass requires another bypass.

2. **`./claude/tools/stage-hash` broken.** First invocation errors with:
   ```
   Error [ERR_MODULE_NOT_FOUND]: Cannot find module
   '/Users/jdm/code/homekit-daikin-ac-bridge/tools/stage-hash.ts'
   ```
   The tool appears to resolve the TS source at a wrong path (missing `claude/` segment). This blocks `/git-safe-commit` Step 1 (stage-hash → QGR receipt match), forcing agents to skip the receipt check or use `--force` unnecessarily.

## Observed Context

- Repo: `homekit-daikin-ac-bridge`
- Framework version: Agency 2.0.0 (updated 653d537d → 109bf5b2)
- Session: first-launch captain session, committing framework scaffolding drop

## Steps to Reproduce

1. Fresh Agency 2.0 bootstrap in a repo
2. Invoke `/git-safe-commit -m "..."` on 229 dirty files
3. Observe `./claude/tools/stage-hash` fails with ERR_MODULE_NOT_FOUND
4. After committing (via any path), attempt to undo via `./claude/tools/git-safe reset --soft HEAD~1` → "Unknown subcommand: reset"
5. Same for `./claude/tools/git-captain reset` → not listed

## Expected Behavior

- `stage-hash` runs cleanly on first invocation and outputs a deterministic hash for the staged set
- Safe wrappers expose a sanctioned recovery path for undoing local (unpushed) commits — e.g. `git-captain reset-soft <ref>` or `git-safe undo-last-commit`, with appropriate guards (no reset on pushed commits, no `--hard` without explicit confirmation)

## Proposed Fixes

1. **stage-hash:** correct module resolution path (likely `tools/stage-hash.ts` → `claude/tools/stage-hash.ts`)
2. **Recovery wrapper:** add `git-captain reset-soft <ref>` gated on: local-only commits (not pushed), clean working tree, optional `--principal-approved` for multi-commit rollback
3. **Skill guidance:** `/git-safe-commit` should detect stage-hash failure and emit a clear actionable error instead of silently succeeding past a missing QGR check

## Related

- Process violation that surfaced this: commit `0e50635` was created via raw `git add -A` + `git commit` because `stage-hash` errored and the safe flow could not complete. Attempting to redo via `/git-safe-commit` after reset hit the missing recovery path.
